-- ============================================================
-- VEESHAL.ME CMS — seed data (mirrors the current static site)
-- ============================================================

delete from public.social_links;
delete from public.featured_projects;
delete from public.gallery;
delete from public.projects;
delete from public.skills;
delete from public.timeline_events;
delete from public.chaicode_items;
delete from public.blogs;

insert into public.site_settings (key, value) values ('resume_url', '"RESUME - VEESHAL.pdf"'::jsonb) on conflict (key) do update set value = excluded.value, updated_at = now();
insert into public.site_settings (key, value) values ('contact_email', '"veebodosa@gmail.com"'::jsonb) on conflict (key) do update set value = excluded.value, updated_at = now();
insert into public.site_settings (key, value) values ('hero', '{"eyebrow": "creative developer \u2014 video editor", "title_1": "code", "title_2": "cinema", "copy": "Welcome to a visual journey that blends code & creativity, where every edit tells a story. Engineered with precision & crafted with passion."}'::jsonb) on conflict (key) do update set value = excluded.value, updated_at = now();
insert into public.site_settings (key, value) values ('stats', '[{"value": 5, "suffix": "", "label": "Developed Live", "link_text": "Coding Projects", "link": "projects"}, {"value": 15, "suffix": "", "label": "Edited High-Quality", "link_text": "Video Projects", "link": "projects"}, {"value": 50, "suffix": "k", "label": "Monthly Visitors for", "link_text": "Bodo Okhrang", "link": "https://bodookhrang.com"}]'::jsonb) on conflict (key) do update set value = excluded.value, updated_at = now();

insert into public.social_links (label, url, sort) values ('yt', 'https://www.youtube.com/@vxwshxl', 0);
insert into public.social_links (label, url, sort) values ('ig', 'https://www.instagram.com/vxwshxl', 1);
insert into public.social_links (label, url, sort) values ('git', 'https://github.com/vxwshxl', 2);
insert into public.social_links (label, url, sort) values ('in', 'https://www.linkedin.com/in/vxwshxl', 3);
insert into public.social_links (label, url, sort) values ('x', 'https://x.com/vxwshxl', 4);
insert into public.social_links (label, url, sort) values ('fb', 'https://www.facebook.com/vxwshxl', 5);

insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('A.I. Tool', 'Bodo Okhrang', 'Web Development', 'https://bodookhrang.com', null, null, 'assets/projects/1.webp', 0);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('E-COMMERCE Tool', 'FlopShop', 'Web Development/PWA', 'https://flopshop.vercel.app', null, null, 'assets/projects/12.webp', 1);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('A.I. Tool', 'CrewSpace AI', 'Extension', 'https://crewspace-ai.vercel.app', null, null, 'assets/projects/11.webp', 2);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Education', 'Kokrajhar University', 'Web & App Development', 'https://ku-app.in', null, null, 'assets/projects/2.webp', 3);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Travel', 'Trip to Darjeeling', 'Video Editing', 'https://www.youtube.com/watch?v=gNVz83QSoY4', null, null, 'assets/projects/4.webp', 4);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Travel', 'Andaman & Nicobar Islands', 'Video Editing', 'https://www.youtube.com/watch?v=gBvocwLObFQ', null, null, 'assets/projects/5.webp', 5);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Event', 'GOOGLE DEV GROUP - 2025', 'Video Editing', null, 'https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/GDG.mp4', null, 'assets/projects/6.webp', 6);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Event', 'Open Mic RGU - 2025', 'Video Editing', null, 'https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/open-mic.mp4', null, 'assets/projects/7.webp', 7);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Event', 'Badminton Tournament', 'Banner Editing', null, null, 'assets/projects/8.webp', 'assets/projects/8.webp', 8);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Tool', 'BODOअख्रां Pvt. Ltd. Logo', 'Logo Design', null, null, 'assets/projects/9.webp', 'assets/projects/9.webp', 9);
insert into public.featured_projects (info, name, tag, url, video, image, hover_src, sort) values ('Local Shop', 'My Tea', 'Banner Editing', null, null, 'assets/projects/10.webp', 'assets/projects/10.webp', 10);

insert into public.gallery (image_url, alt, sort) values ('assets/portfolio/1.webp', 'Portfolio 1', 0);
insert into public.gallery (image_url, alt, sort) values ('assets/portfolio/2.webp', 'Portfolio 2', 1);
insert into public.gallery (image_url, alt, sort) values ('assets/portfolio/3.webp', 'Portfolio 3', 2);
insert into public.gallery (image_url, alt, sort) values ('assets/portfolio/4.webp', 'Portfolio 4', 3);
insert into public.gallery (image_url, alt, sort) values ('assets/portfolio/5.webp', 'Portfolio 5', 4);
insert into public.gallery (image_url, alt, sort) values ('assets/portfolio/6.webp', 'Portfolio 6', 5);

insert into public.skills (name, icon_url, sort) values ('React Native', 'assets/skills/react-native.png', 0);
insert into public.skills (name, icon_url, sort) values ('Flutter', 'assets/skills/flutter.png', 1);
insert into public.skills (name, icon_url, sort) values ('Tailwind CSS', 'assets/skills/tailwind.png', 2);
insert into public.skills (name, icon_url, sort) values ('Expo', 'assets/skills/expo.png', 3);
insert into public.skills (name, icon_url, sort) values ('PHP', 'assets/skills/php.png', 4);
insert into public.skills (name, icon_url, sort) values ('MySQL', 'assets/skills/mysql.png', 5);
insert into public.skills (name, icon_url, sort) values ('PostgreSQL', 'assets/skills/postgreSQL.png', 6);
insert into public.skills (name, icon_url, sort) values ('Adobe Premiere', 'assets/skills/premiere.png', 7);
insert into public.skills (name, icon_url, sort) values ('DaVinci Resolve', 'assets/skills/davinci.png', 8);
insert into public.skills (name, icon_url, sort) values ('CapCut', 'assets/skills/capcut.png', 9);
insert into public.skills (name, icon_url, sort) values ('Figma', 'assets/skills/figma.png', 10);
insert into public.skills (name, icon_url, sort) values ('Krita', 'assets/skills/krita.png', 11);
insert into public.skills (name, icon_url, sort) values ('Canva', 'assets/skills/canva.png', 12);
insert into public.skills (name, icon_url, sort) values ('Jitter', 'assets/skills/jitter.png', 13);

insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Bodo Okhrang', 'development', 'A.I. Tool — Web Development', 'assets/projects/1.webp', 'An <strong>AI-powered Anglo-Bodo dictionary</strong> and language platform built for the Bodo community. Instant word lookup, smart suggestions and a clean reading experience — now serving <strong>50,000+ visitors every month</strong> and growing.', 'Full-stack Developer', 'PHP · MySQL · JS · AI', '2024 — live', 'visit live site', 'https://bodookhrang.com', null, null, 0);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('FlopShop', 'development', 'E-commerce — PWA', 'assets/projects/12.webp', 'A modern <strong>e-commerce progressive web app</strong> — installable, offline-friendly and fast on any device. Snappy product browsing, cart flow and a checkout experience that feels native.', 'Designer & Developer', 'React · PWA · Vercel', '2025 — live', 'visit live site', 'https://flopshop.vercel.app', null, null, 1);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('CrewSpace AI', 'development', 'A.I. Tool — Browser Extension', 'assets/projects/11.webp', 'A <strong>browser extension</strong> that brings AI assistance straight into your workspace — summarise, draft and organise without ever leaving the tab you are working in.', 'Creator & Developer', 'JS · Extension APIs · AI', '2025 — live', 'visit live site', 'https://crewspace-ai.vercel.app', null, null, 2);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Kokrajhar University', 'development', 'Education — Web & App', 'assets/projects/2.webp', 'The digital front door for <strong>Kokrajhar University</strong> — a website and companion app giving students notices, resources and campus information in one organised, mobile-first place.', 'Web & App Developer', 'PHP · MySQL · React Native', '2024 — live', 'visit live site', 'https://ku-app.in', null, null, 3);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Swrzee Enterprise', 'development', 'Enterprise — Web Development', 'assets/projects/3.webp', 'A clean, credible <strong>business website</strong> for Swrzee Enterprise — product showcase, company story and contact flows designed to convert visitors into customers.', 'Designer & Developer', 'PHP · CSS · JS', '2024 — live', 'visit live site', 'https://swrzee.in', null, null, 4);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Trip to Darjeeling', 'video', 'Travel Film — Video Editing', 'assets/projects/4.webp', 'A <strong>cinematic travel film</strong> through the hills of Darjeeling — tea gardens, toy trains and misty ridgelines, cut to rhythm with colour grading that keeps the mountain mood intact.', 'Editor & Colorist', 'Premiere · DaVinci', '2024', 'watch the film', 'https://www.youtube.com/watch?v=gNVz83QSoY4', null, null, 5);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Andaman & Nicobar Islands', 'video', 'Travel Film — Video Editing', 'assets/projects/5.webp', 'Island hopping, turquoise water and slow sunsets — a <strong>travel edit</strong> built around pacing: fast cuts on the boats, long breaths on the beaches.', 'Editor & Colorist', 'Premiere · DaVinci', '2024', 'watch the film', 'https://www.youtube.com/watch?v=gBvocwLObFQ', null, null, 6);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Google Dev Group — 2025', 'video', 'Event — Video Editing', 'assets/projects/6.webp', 'Official <strong>aftermovie for the Google Developer Group 2025</strong> event — talks, crowd energy and behind-the-scenes moments compressed into a tight, high-energy recap.', 'Editor', 'Premiere · CapCut', '2025', 'watch the film', null, 'https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/GDG.mp4', null, 7);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Open Mic RGU — 2025', 'video', 'Event — Video Editing', 'assets/projects/7.webp', 'An <strong>event recap</strong> of Open Mic at RGU — raw performances, audience reactions and stage lights, edited to keep the live-room feeling on screen.', 'Editor', 'Premiere · CapCut', '2025', 'watch the film', null, 'https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/open-mic.mp4', null, 8);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('Badminton Tournament', 'design', 'Event — Banner Design', 'assets/projects/8.webp', 'A bold <strong>tournament banner</strong> — strong type hierarchy, action photography and a layout that reads clearly from across a hall or in a feed.', 'Designer', 'Figma · Canva', '2024', 'view the design', null, null, 'assets/projects/8.webp', 9);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('BODOअख्रां Pvt. Ltd. Logo', 'design', 'Brand — Logo Design', 'assets/projects/9.webp', 'Identity work for <strong>BODOअख्रां Pvt. Ltd.</strong> — a mark that blends Devanagari character with a modern wordmark, built to hold up from favicon to billboard.', 'Brand Designer', 'Figma · Krita', '2024', 'view the design', null, null, 'assets/projects/9.webp', 10);
insert into public.projects (title, cat, cat_label, img, description, role, stack, year, action, url, video, image, sort) values ('My Tea', 'design', 'Local Shop — Banner Design', 'assets/projects/10.webp', 'A warm, appetising <strong>storefront banner</strong> for a local tea shop — friendly type, rich colour and a layout that makes you want a cup immediately.', 'Designer', 'Canva · Krita', '2024', 'view the design', null, null, 'assets/projects/10.webp', 11);

insert into public.timeline_events (title, description, tag, date_label, images, sort) values ('AI & Innovation at NEGC 2026, USTM', 'AI & Innovation... Awarded competition conducted during North East Graduate Congress-2026 held at University of Science & Technology Meghalaya from 26th–28th March, 2026.', 'Winner', '26-28 Mar 2026', '["https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/AI%20%26%20Inno%202026%20-%201st.webp", "https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/AI%20%26%20Inno%20-%201.webp", "https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/AI%20%26%20Inno%20-%202.webp"]'::jsonb, 0);
insert into public.timeline_events (title, description, tag, date_label, images, sort) values ('Prajukti 2026 GCU Hackathon', 'Prajukti 2026 GCU Hackathon held during GCU Varsity Week: EUPHUISM 2026 (Roots and Resilience) from 11th to 14th March, 2026.', 'Winner', '11-14 Mar 2026', '["https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/Prajukti%202026%20-%201st.webp", "https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/Prajukti%20-%201.webp", "https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/Prajukti%20-%202.webp"]'::jsonb, 1);
insert into public.timeline_events (title, description, tag, date_label, images, sort) values ('Codestellation, under CodeWar 7.0 at AEC', 'This Hackathon was held by Assam Engineering College (AEC) under CodeWar 7.0 part of Pyrokinesis 2026 organised by Coding Club, AEC named as Codestellation on 26 Feb 2026.', 'First Runner Up', '26 Feb 2026', '["https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/CodeWar%202026%20-%202nd.webp", "https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/CodeWar%20-%201.webp", "https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/CodeWar%20-%202.webp"]'::jsonb, 2);
insert into public.timeline_events (title, description, tag, date_label, images, sort) values ('Ideathon — Where Ideas Compile', 'First place at the Ideathon competition — a stage where raw ideas meet real execution. Pitched a solution that stood out from the crowd and brought home the win. The beginning of the grind.', 'Winner', '27 NOV 2024', '["https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/achievement/Idea%20Comp%202024%20-%201st.webp"]'::jsonb, 3);

insert into public.chaicode_items (title, category, date_label, image, link, sort) values ('Mintlify - The Intelligent Documentation Platform', 'Web Development', '06 Feb 2026', 'https://raw.githubusercontent.com/vxwshxl/veeshal/refs/heads/main/public/chaicode/mintlify/assets/mintlify.webp', 'mintlify', 0);
insert into public.chaicode_items (title, category, date_label, image, link, sort) values ('Cursor', 'Web Development', '04 Feb 2026', 'https://raw.githubusercontent.com/vxwshxl/veeshal/refs/heads/main/public/chaicode/cursor/assets/cursor.webp', 'cursor', 1);
insert into public.chaicode_items (title, category, date_label, image, link, sort) values ('HTML Resume Page Assignment', 'Web Development', '30 Jan 2026', 'https://veeshal.me/assets/vee-img.webp', 'resume.html', 2);

insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('JavaScript Operators: The Basics You Need to Know', 'javascript-operators-basics', 'JavaScript', '15 Mar 2026', 'https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fgd13jf7crx0nffnb0szj.jpg', true, 0);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('The Magic of this, call(), apply(), and bind() in JavaScript', 'the-magic-of-this-call-apply-bind-in-javascript', 'JavaScript', '15 Mar 2026', 'https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F2z8d8uo9p763mb5mc1rn.webp', true, 1);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Function Declaration vs Function Expression: What’s the Difference?', 'function-declaration-vs-function-expression', 'JavaScript', '15 Mar 2026', 'https://blog.thitainfo.com/_next/image?url=https%3A%2F%2Fcdn.hashnode.com%2Fuploads%2Fcovers%2F6185effafd5d634d0169926f%2Fc896a9b8-0227-4b9a-9323-6d48e02e2427.png&w=3840&q=75', true, 2);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('JavaScript Arrays 101', 'javascript-arrays-101', 'JavaScript', '15 Mar 2026', 'https://media2.dev.to/dynamic/image/width=1280,height=720,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ftqo1rab6eznma8tzwzcl.webp', true, 3);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Understanding Object-Oriented Programming in JavaScript', 'understanding-oop-in-javascript', 'JavaScript', '15 Mar 2026', 'https://miro.medium.com/0*wgDCQoZtprrPg272.jpg', true, 4);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Understanding Objects in JavaScript', 'understanding-objects-in-javascript', 'JavaScript', '15 Mar 2026', 'https://blog.thitainfo.com/_next/image?url=https%3A%2F%2Fcdn.hashnode.com%2Fuploads%2Fcovers%2F6185effafd5d634d0169926f%2F5e436a36-838c-42ca-8340-8fb929ad9fc8.png&w=3840&q=75', true, 5);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Understanding Variables and Data Types in JavaScript', 'understanding-variables-and-data-types-in-javascript', 'JavaScript', '15 Mar 2026', 'https://miro.medium.com/v2/resize:fit:1400/format:webp/1*qvAJkRLtYnnVFTScPjgWPA.jpeg', true, 6);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Control Flow in JavaScript: If, Else, and Switch Explained', 'control-flow-in-javascript', 'JavaScript', '15 Mar 2026', 'https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ej4NUhE3AOp0DVBJR3WA5w.png', true, 7);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Arrow Functions in JavaScript: A Simpler Way to Write Functions', 'arrow-functions-in-javascript', 'JavaScript', '15 Mar 2026', 'https://miro.medium.com/v2/resize:fit:1400/format:webp/0*-OKyZav_Yo-3ZIrb', true, 8);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Array Methods You Must Know', 'array-methods-you-must-know', 'JavaScript', '15 Mar 2026', 'https://miro.medium.com/v2/resize:fit:1400/1*-1JKUVOs2X9xkmIb-KmKKA.jpeg', true, 9);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Emmet for HTML: A Beginner’s Guide to Writing Faster Markup', 'emmet-for-html', 'HTML & CSS', '27 Jan 2026', 'https://www.alphr.com/wp-content/uploads/2023/10/emmet-nedir-ve-ne-ise-yarar-1280x720.jpg', true, 10);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('CSS Selectors 101: Targeting Elements with Precision', 'css-selectors-101', 'HTML & CSS', '25 Jan 2026', 'https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fnl1rxl108tb77t4ch3g3.png', true, 11);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Understanding HTML Tags and Elements', 'understanding-html-tags-and-elements', 'HTML & CSS', '24 Jan 2026', 'https://i.ytimg.com/vi/mekRKzHByEQ/maxresdefault.jpg', true, 12);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('How a Browser Works: A Beginner-Friendly Guide', 'how-a-browser-works', 'HTML & CSS', '23 Jan 2026', 'https://ineasysteps.com/wp-content/uploads/2021/11/How-to-web-browsers-work-image.jpg', true, 13);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('TCP Working: 3-Way Handshake & Reliable Communication', 'tcp-working', 'Software development', '22 Jan 2026', 'https://i.ytimg.com/vi/_inkLnDbia0/sddefault.jpg', true, 14);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('TCP vs UDP: When to Use What', 'tcp-vs-udp', 'Software development', '21 Jan 2026', 'https://miro.medium.com/v2/resize:fit:1400/format:webp/1*ZPtAG6N2qQB_iIFzEtPP7Q.png', true, 15);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Understanding Network Devices', 'understanding-network-devices', 'Software development', '20 Jan 2026', 'https://media2.dev.to/dynamic/image/width=1280,height=720,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F9uj3ypmyimbvite0dgu2.jpeg', true, 16);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('How DNS Resolution Works', 'how-dns-resolution-works', 'Software development', '19 Jan 2026', 'https://media.geeksforgeeks.org/wp-content/uploads/20250801171021517035/address_resolution_in_dns.webp', true, 17);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Getting Started with cURL', 'getting-started-with-curl', 'Software development', '18 Jan 2026', 'https://curl.se/logo/curl-logo.svg', true, 18);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('DNS Record Types Explained', 'dns-record-types-explained', 'Software development', '17 Jan 2026', 'https://www.cloudflare.com/img/learning/dns/what-is-dns/dns-lookup-diagram.png', true, 19);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Why Version Control Exists: The Pendrive Problem', 'why-version-control-exists', 'Software development', '16 Jan 2026', 'https://media2.dev.to/dynamic/image/width=1280,height=720,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fmjsud8ijzeytlosc6w49.png', true, 20);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Inside Git: How It Works and the Role of the .git Folder', 'inside-git-how-it-works', 'Software development', '16 Jan 2026', 'https://camo.githubusercontent.com/79c5248e3ba42801c55213b83f56bc8e0d39ebf6834498e56e9733f0fa87ccf4/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f76322f726573697a653a6669743a313430302f312a36536278616a4d6468536639365073507972545a47672e706e67', true, 21);
insert into public.blogs (title, slug, category, date_label, image, is_static, sort) values ('Git for Beginners: Basics and Essential Commands', 'git-for-beginners', 'Software development', '13 Jan 2026', 'https://pub-fe9b85f97c6a4773bbf0ceb5f53c430b.r2.dev/blogs/git-for-beginners/working-dir.png', true, 22);
